### ISSUE TITLE
Delete of an unknown package fails with a wrong error

### ISSUE THREAD

**Issue by durango** [mbrevoort/node-reggie#13]
Keep getting a {"code":"InternalError","message":"Object.keys called on non-object"} error whenever I try to delete a package

```
 curl -X DELETE http://localhost:8080/package/mypackage/0.0.1
```

**Comment by durango** [comment]
Nevermind, it might be a bug with npm itself.. whenever I do ..

npm --registry=http://npm.dev.ourmachineatwork.com

it keeps trying to do...

```
npm http PUT http://127.0.0.1:8989/package
npm http 200 http://127.0.0.1:8989/package
npm http GET http://127.0.0.1:8989/package
npm http 200 http://127.0.0.1:8989/package
```

which is obviously wrong :/

**Comment by bajtos** [comment]
@durango What are your versions of node-reggie and npm/node? What is the exact command-line you used for deleting a package?

**Comment by durango** [comment]
@bajtos  latest for node-reggie, node and npm are..

node v0.8.25 (I know old)
npm 1.3.6

The problem was... I deleted the package successfully actually initially but then when I went to delete again it gave me the Object.keys error (I delete via curl -X DELETE btw). NPM was saying package-0.0.1 already exists (but that's because I'm running a locla instance of reggie as well).

So, in short, the error is simply when I'm trying to delete it gives me an Object.keys error if that version / package doesn't even remotely exists (perhaps it should be a 404? I'm not entirely sure what npmjs does tbh).

Here's an example of my Makefile...

``` Makefile
REPO ?= http://fakecompanydev.com
NAME_CMD := cat package.json | grep -m 1 -o '"name":\s*"\([^"]\)*"' | sed 's/"name":[^"]*"\(.*\)"$$/\1/'
VERSION_CMD := cat package.json | grep -m 1 -o '"version":\s*"\([^"]\)*"' | sed 's/"version":[^"]*"\(.*\)"$$/\1/'

build delete clean : PACKAGE_NAME:=$(shell ${NAME_CMD})
build delete : PACKAGE_VERSION:=$(shell ${VERSION_CMD})

clean:
    @rm -rf ./node_modules
    @rm -rf ./${PACKAGE_NAME}*.tgz
    @rm -rf *.log
    @rm -rf .DS_STORE

pack: clean
    @npm pack

build: delete
    @reggie -u http://${REPO}/ publish

delete:
    # @npm --registry=http://${REPO}/ unpublish ${PACKAGE_NAME}@${PACKAGE_VERSION} # Not supported yet...
    @curl -X DELETE http://${REPO}/package/${PACKAGE_NAME}/${PACKAGE_VERSION}

.PHONY: clean pack delete build
```

**Comment by bajtos** [comment]
Thanks for a detailed explanation. I'll mark the issue as bug, unfortunately I don't have time to fix it now.

**Comment by durango** [comment]
Not a problem, I'd offer to help but the stack trace is rather.. limited heh. If I find the time I'll be more than happy to help contribute / if you don't beat me in time heh.

**Comment by paolodm** [comment]
This should be fixed in #22.

It now gives the error message 

```
{"code":"InternalError","message":"Cannot read property 'versions' of undefined"} 
```

which is a bad error message. I'd be happy to change the error message to something a bit more intelligible once #22 gets approved.

**Comment by bajtos** [comment]
#22 did not fix the issue, the error message is still there.

**Comment by bajtos** [comment]
Fixed in v0.1.8.
